### ISSUE TITLE
The form is expired, try again

### ISSUE THREAD

**Issue by bas-hendriks** [ndijkstra/doneren-met-mollie#8]
When I'm using an iPad on the safari browser I get the message when I am trying to donate: 
NL: "Het formulier is verlopen, probeer het opnieuw"
EN: "The form has expired, try again"

This message pops up when I select iDeal and when i click on a bank. This only happens on Safari on iPad.
![bestand_000](https://user-images.githubusercontent.com/19948878/28872889-6653cf1c-778b-11e7-8b6b-ac86ddef28b3.png)

**Comment by ndijkstra** [comment]
Hi Bas,

Is this only on the iPad in Safari?

**Comment by bas-hendriks** [comment]
Yes only on iPad (not iPhone, android, imac, pc) and only in the safari browser

**Comment by ndijkstra** [comment]
Mmm, interesting. I think this is something in the Mollie Payment screen. I will create an issue for Mollie. I'll keep you posted.

**Comment by bas-hendriks** [comment]
Hey Nick, got any news for me? I have to keep the client posted.

**Comment by ndijkstra** [comment]
Not yet, I will inform you today.

**Comment by ndijkstra** [comment]
Sorry for the late response, but Mollie and I can't reproduce this problem.
Can you try it again to see if it's fixed already?
